name: movies_app_flutter
description: A new Flutter project.
publish_to: "none"

version: 0.0.2+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  http: ^0.13.6
  path_provider: ^2.1.2
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/details_background.jpg
